name: foodsteradmin
description: A new Flutter project.


publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  get: ^4.6.1
  image_picker: ^0.8.4+4
  flutter_svg: ^1.0.0
  firebase_core: ^1.11.0
  firebase_database: ^9.0.5
  firebase_storage: ^10.2.5
  cached_network_image: ^3.2.0
  flutter_spinkit: ^5.1.0
  intl: ^0.17.0
  shared_preferences: ^2.0.12
  csv: ^5.0.1
  path_provider: ^2.0.9
  flutter_email_sender: ^5.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^1.0.0


flutter:


  uses-material-design: true


  assets:
      - assets/images/
      - assets/svg/

  fonts:
      - family: rubik_light
        fonts:
          - asset: assets/fonts/rubik_light.ttf
      - family: rubik_regular
        fonts:
          - asset: assets/fonts/rubik_regular.ttf


